import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    include: ['src/**/*.test.ts'],
    exclude: [
      // node:test files — run via `node --test`, not vitest
      'src/commands/__tests__/team-preflight.test.ts',
      'src/commands/__tests__/coordinate-watch.test.ts',
      'src/commands/__tests__/coordinate-report.test.ts',
      'src/commands/delegate.test.ts',
      'src/commands/install-ui/BlueprintPreview.logic.test.ts',
      'src/commands/install-ui/ComponentGrid.logic.test.ts',
      'src/mcp/delegate-channel-relay.test.ts',
      'src/async/delegate-broker.test.ts',
      'src/async/delegate-e2e.test.ts',
      'src/async/delegate-control.test.ts',
      'src/agents/cli-agent-runner.test.ts',
      'src/hooks/delegate-monitor.test.ts',
      'src/hooks/__tests__/coordinator-tracker-integration.test.ts',
      'src/hooks/__tests__/coordinator-tracker.test.ts',
      'src/hooks/__tests__/workspace.test.ts',
      'src/hooks/__tests__/skill-context.test.ts',
      'src/hooks/__tests__/spec-injector.test.ts',
      'src/hooks/__tests__/session-context.test.ts',
      'src/hooks/__tests__/evaluate-guards.test.ts',
      'src/hooks/__tests__/plugins.test.ts',
      'src/hooks/__tests__/hook-engine.test.ts',
      'src/hooks/__tests__/statusline-team.test.ts',
      'src/hooks/__tests__/team-monitor.test.ts',
      'src/coordinator/__tests__/graph-loader.test.ts',
      'src/coordinator/__tests__/graph-walker.test.ts',
      'src/coordinator/__tests__/graph-walker-llm-decision.test.ts',
      'src/coordinator/__tests__/graph-walker-report.test.ts',
      'src/coordinator/__tests__/llm-decider.test.ts',
      'src/coordinator/__tests__/coordinate-broker-adapter.test.ts',
      'src/coordinator/__tests__/prompt-assembler.test.ts',
      'src/coordinator/__tests__/intent-router.test.ts',
      'src/coordinator/__tests__/expr-evaluator.test.ts',
      'src/coordinator/__tests__/output-parser.test.ts',
      'src/tools/__tests__/spec-loader.test.ts',
      'src/tools/__tests__/team-members.test.ts',
      'src/tools/__tests__/team-activity.test.ts',
      'src/tools/__tests__/transition-recorder.test.ts',
      'src/utils/__tests__/jsonl-log.test.ts',
    ],
    environment: 'node',
    root: resolve(__dirname),
  },
});
