/**
 * Knowledge Graph Command — CLI for querying codebase knowledge graphs.
 *
 * Subcommands: stats, query, explain, path, diff, diff-wiki, search, context
 *
 * Operates on `.workflow/codebase/knowledge-graph.json` generated by
 * compatible code analyzers.
 */

import type { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import type { KnowledgeGraph, GraphNode } from '../graph/types.js';
import { loadGraph } from '../graph/loader.js';
import { searchNodes, findPath, diffChanges, countBy, truncate } from '../graph/query.js';
import { FsAnalyzer } from '../graph/analyzers/fs-analyzer.js';
import { DatabaseConnection, getDatabasePath, QueryBuilder } from '../graph/db/index.js';
import { GraphTraverser } from '../graph/traversal.js';
import { GraphQueryManager } from '../graph/graph-queries.js';
import { IncrementalSync } from '../graph/sync/incremental-sync.js';
import { FileWatcher } from '../graph/sync/watcher.js';
import { parseQuery } from '../graph/search/query-parser.js';
import { migrateJsonToSqlite, exportSqliteToJson } from '../graph/migration.js';

import { WikiIndexer } from '#maestro-dashboard/wiki/wiki-indexer.js';
import type { WikiEntry } from '#maestro-dashboard/wiki/wiki-types.js';

function loadGraphOrExit(): KnowledgeGraph {
  try {
    return loadGraph();
  } catch (err) {
    console.error((err as Error).message);
    console.error('  Hint: generate one with a compatible code analyzer');
    process.exit(1);
  }
}

// ── Wiki cross-reference ──────────────────────────────────────────────

let _wikiIndexer: WikiIndexer | null = null;
function getWikiIndexer(): WikiIndexer | null {
  if (_wikiIndexer) return _wikiIndexer;
  const workflowRoot = resolve('.workflow');
  if (!existsSync(workflowRoot)) return null;
  _wikiIndexer = new WikiIndexer({ workflowRoot });
  return _wikiIndexer;
}

interface WikiMatch {
  id: string;
  type: string;
  title: string;
  matchReason: string;
}

async function findRelatedWikiEntries(nodeId: string, filePath?: string): Promise<WikiMatch[]> {
  const indexer = getWikiIndexer();
  if (!indexer) return [];
  try {
    const index = await indexer.get();
    const matches: WikiMatch[] = [];
    const seen = new Set<string>();

    for (const e of index.entries) {
      if (seen.has(e.id)) continue;
      if (e.ext?.virtualKind === 'kg-node' && e.ext?.kgNodeId === nodeId) {
        seen.add(e.id);
        matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'kg-node-entry' });
        continue;
      }
      if (filePath && Array.isArray(e.ext?.codeLocations)) {
        const locs = e.ext.codeLocations as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (locs.some(l => l.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
      if (seen.has(e.id)) continue;
      if (filePath && Array.isArray(e.ext?.codePaths)) {
        const paths = e.ext.codePaths as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (paths.some(p => p.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
    }
    return matches;
  } catch {
    return [];
  }
}

// ── SQLite helpers ────────────────────────────────────────────────────

function openSqliteOrExit(): { conn: DatabaseConnection; queries: QueryBuilder } {
  const dbPath = getDatabasePath();
  if (!existsSync(dbPath)) {
    console.error(`SQLite graph not found: ${dbPath}`);
    console.error('  Hint: run "maestro kg index --sqlite" to create one');
    process.exit(1);
  }
  const conn = new DatabaseConnection();
  conn.open(dbPath);
  return { conn, queries: new QueryBuilder(conn) };
}

function hasSqliteDb(): boolean {
  return existsSync(getDatabasePath());
}

// ── Registration ───────────────────────────────────────────────────────

export function registerKgCommand(program: Command): void {
  const kg = program
    .command('kg')
    .description('Query codebase knowledge graph (JSON or SQLite backend)');

  // ── stats ──────────────────────────────────────────────────────────
  kg
    .command('stats')
    .description('Display knowledge graph statistics')
    .option('--json', 'Output as JSON')
    .action((_opts) => {
      const graph = loadGraphOrExit();
      const nodesByType = countBy(graph.nodes, n => n.type);
      const edgesByType = countBy(graph.edges, e => e.type);

      const data = {
        project: graph.project.name,
        version: graph.version,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
      };

      if (_opts.json) {
        console.log(JSON.stringify(data, null, 2));
        return;
      }

      console.log(`Knowledge Graph: ${data.project} (v${data.version})`);
      console.log('');
      console.log(`Nodes: ${data.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${data.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${data.layers}`);
      console.log(`Tour steps: ${data.tourSteps}`);
    });

  // ── query ──────────────────────────────────────────────────────────
  kg
    .command('query <text>')
    .description('Search nodes by name, summary, or tags')
    .option('--limit <n>', 'Max results', '10')
    .option('--type <nodeType>', 'Filter by node type')
    .option('--json', 'Output as JSON')
    .action((text: string, opts) => {
      const limit = Number(opts.limit) || 10;

      if (hasSqliteDb()) {
        const { conn, queries } = openSqliteOrExit();
        try {
          const parsed = parseQuery(text);
          const kinds = parsed.kinds.length > 0 ? parsed.kinds : undefined;
          const results = queries.searchNodes(parsed.text || text, {
            kinds,
            languages: parsed.languages.length > 0 ? parsed.languages : undefined,
            pathFilters: parsed.pathFilters.length > 0 ? parsed.pathFilters : undefined,
            nameFilters: parsed.nameFilters.length > 0 ? parsed.nameFilters : undefined,
            limit,
          });

          if (opts.json) {
            console.log(JSON.stringify({ query: text, total: results.length, nodes: results }, null, 2));
            return;
          }

          console.log(`Query: "${text}"  (${results.length} results, SQLite)`);
          for (const n of results) {
            const exported = n.isExported ? 'Exported ' : '';
            const desc = n.signature ? truncate(n.signature, 60) : `${exported}${n.kind} "${n.name}" in ${n.filePath}`;
            console.log(`  [${n.kind}] ${n.id} -- ${desc}`);
          }
        } finally {
          conn.close();
        }
        return;
      }

      const graph = loadGraphOrExit();
      const matches = searchNodes(graph, text, { limit, type: opts.type });
      const total = searchNodes(graph, text, { limit: Infinity, type: opts.type }).length;

      if (opts.json) {
        console.log(JSON.stringify({ query: text, total, nodes: matches }, null, 2));
        return;
      }

      console.log(`Query: "${text}"  (${matches.length}/${total} results)`);
      for (const n of matches) {
        console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 80)}`);
      }
    });

  // ── explain ────────────────────────────────────────────────────────
  kg
    .command('explain <node-id>')
    .description('Show full details of a node and its connections')
    .option('--json', 'Output as JSON')
    .option('--no-wiki', 'Skip wiki cross-reference lookup')
    .action(async (nodeId: string, opts) => {
      const graph = loadGraphOrExit();
      const node = graph.nodes.find(n => n.id === nodeId);

      if (!node) {
        console.error(`Node not found: ${nodeId}`);
        process.exit(1);
      }

      const incoming = graph.edges.filter(e => e.target === nodeId);
      const outgoing = graph.edges.filter(e => e.source === nodeId);
      const layers = graph.layers.filter(l => l.nodeIds.includes(nodeId));

      const wikiMatches = opts.wiki !== false
        ? await findRelatedWikiEntries(nodeId, node.filePath)
        : [];

      if (opts.json) {
        console.log(JSON.stringify({ node, incoming, outgoing, layers, wiki: wikiMatches }, null, 2));
        return;
      }

      console.log(`Node: ${node.id}`);
      console.log(`  Type:       ${node.type}`);
      console.log(`  Name:       ${node.name}`);
      if (node.filePath) console.log(`  File:       ${node.filePath}`);
      console.log(`  Summary:    ${node.summary}`);
      if (node.tags?.length) console.log(`  Tags:       ${node.tags.join(', ')}`);
      if (node.complexity) console.log(`  Complexity: ${node.complexity}`);

      if (layers.length > 0) {
        console.log('');
        console.log('Layers:');
        for (const l of layers) {
          console.log(`  ${l.id} -- ${l.name}`);
        }
      }

      if (incoming.length > 0) {
        console.log('');
        console.log(`Incoming edges (${incoming.length}):`);
        for (const e of incoming) {
          console.log(`  ${e.source} --${e.type}--> ${nodeId}`);
        }
      }

      if (outgoing.length > 0) {
        console.log('');
        console.log(`Outgoing edges (${outgoing.length}):`);
        for (const e of outgoing) {
          console.log(`  ${nodeId} --${e.type}--> ${e.target}`);
        }
      }

      if (wikiMatches.length > 0) {
        console.log('');
        console.log(`Related wiki entries (${wikiMatches.length}):`);
        for (const w of wikiMatches) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
        }
      }
    });

  // ── path ───────────────────────────────────────────────────────────
  kg
    .command('path <from-id> <to-id>')
    .description('Find shortest path between two nodes (BFS, undirected)')
    .option('--json', 'Output as JSON')
    .action((fromId: string, toId: string, opts) => {
      const graph = loadGraphOrExit();

      try {
        const result = findPath(graph, fromId, toId);

        if (!result.found) {
          if (opts.json) {
            console.log(JSON.stringify({ from: fromId, to: toId, path: null, message: 'No path found' }, null, 2));
          } else {
            console.log(`No path found from ${fromId} to ${toId}`);
          }
          return;
        }

        if (opts.json) {
          console.log(JSON.stringify({ from: fromId, to: toId, length: result.length, steps: result.steps }, null, 2));
          return;
        }

        console.log(`Path: ${fromId} -> ${toId}  (${result.length} hops)`);
        console.log('');
        for (let i = 0; i < result.steps.length; i++) {
          const step = result.steps[i];
          console.log(`  [${step.type ?? '?'}] ${step.node} -- ${truncate(step.name ?? '', 60)}`);
          if (step.edgeToNext) {
            console.log(`    | ${step.edgeToNext}`);
          }
        }
      } catch (err) {
        console.error((err as Error).message);
        process.exit(1);
      }
    });

  // ── diff ───────────────────────────────────────────────────────────
  kg
    .command('diff')
    .description('Show KG nodes affected by git changes')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const graph = loadGraphOrExit();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], direct: [], impacted: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      const result = diffChanges(graph, changedFiles);

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log('');

      console.log(`Direct (${result.direct.length}):`);
      if (result.direct.length === 0) {
        console.log('  (no KG nodes match changed files)');
      } else {
        for (const n of result.direct) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }

      console.log('');
      console.log(`Impacted (${result.impacted.length}):`);
      if (result.impacted.length === 0) {
        console.log('  (no 1-hop neighbors found)');
      } else {
        for (const n of result.impacted) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }
    });

  // ── diff-wiki ─────────────────────────────────────────────────────
  kg
    .command('diff-wiki')
    .description('Cross-reference git changes with KG nodes and wiki entries')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      const graph = loadGraphOrExit();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], affectedWiki: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      const result = diffChanges(graph, changedFiles);

      // Collect all affected file paths from KG nodes
      const affectedPaths = new Set<string>();
      for (const n of result.direct) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const n of result.impacted) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const f of changedFiles) {
        affectedPaths.add(f.replace(/\\/g, '/').toLowerCase());
      }

      // Cross-reference with wiki
      const indexer = getWikiIndexer();
      const affectedWiki: Array<{ id: string; type: string; title: string; reason: string }> = [];

      if (indexer) {
        try {
          const index = await indexer.get();
          const seen = new Set<string>();
          for (const entry of index.entries) {
            if (seen.has(entry.id)) continue;
            if (Array.isArray(entry.ext?.codeLocations)) {
              const locs = entry.ext.codeLocations as string[];
              for (const loc of locs) {
                if (affectedPaths.has(loc.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codeLocation' });
                  break;
                }
              }
            }
            if (seen.has(entry.id)) continue;
            if (Array.isArray(entry.ext?.codePaths)) {
              const paths = entry.ext.codePaths as string[];
              for (const p of paths) {
                if (affectedPaths.has(p.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codePath' });
                  break;
                }
              }
            }
          }
        } catch { /* wiki unavailable — continue without */ }
      }

      if (opts.json) {
        console.log(JSON.stringify({
          changedFiles,
          directNodes: result.direct.length,
          impactedNodes: result.impacted.length,
          affectedWiki,
        }, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log(`KG direct: ${result.direct.length}, impacted: ${result.impacted.length}`);
      console.log('');

      if (affectedWiki.length === 0) {
        console.log('No wiki entries affected by these changes.');
      } else {
        console.log(`Affected wiki entries (${affectedWiki.length}):`);
        for (const w of affectedWiki) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.reason})`);
        }
      }
    });

  // ── index ─────────────────────────────────────────────────────────
  kg
    .command('index')
    .description('Scan codebase and generate knowledge graph')
    .option('--src <path>', 'Source directory to scan', 'src')
    .option('--sqlite', 'Use SQLite backend (recommended for large projects)')
    .option('--no-codegraph', 'Force regex-only extraction (skip tree-sitter)')
    .option('--json', 'Output stats as JSON after indexing')
    .action(async (opts) => {
      const srcPath = resolve(opts.src);
      if (!existsSync(srcPath)) {
        console.error(`Source directory not found: ${srcPath}`);
        process.exit(1);
      }

      // CodeGraph tree-sitter engine (preferred when available)
      if (opts.codegraph !== false) {
        try {
          const { isCodeGraphAvailable, CodeGraphAdapter } = await import('../graph/codegraph-adapter.js');
          if (isCodeGraphAvailable()) {
            console.log('Using CodeGraph tree-sitter engine...');
            const projectRoot = resolve('.');
            const adapter = new CodeGraphAdapter(projectRoot);
            try {
              const result = await adapter.index({ verbose: true });
              const stats = await adapter.stats();

              if (opts.json) {
                console.log(JSON.stringify({ ...stats, ...result, engine: 'codegraph' }, null, 2));
                return;
              }

              console.log('');
              console.log(`Nodes: ${stats.nodeCount}`);
              for (const [kind, count] of Object.entries(stats.nodesByKind)) {
                console.log(`  ${kind}: ${count}`);
              }
              console.log('');
              console.log(`Edges: ${stats.edgeCount}`);
              for (const [kind, count] of Object.entries(stats.edgesByKind)) {
                console.log(`  ${kind}: ${count}`);
              }
              console.log('');
              console.log(`Files: ${stats.fileCount}`);
              console.log(`DB size: ${(stats.dbSizeBytes / 1024).toFixed(1)} KB`);
              console.log(`Duration: ${result.durationMs}ms`);
              if (result.errors.length > 0) {
                console.log(`Errors: ${result.errors.length}`);
                for (const err of result.errors.slice(0, 5)) {
                  console.log(`  [${err.severity}] ${err.message}${err.filePath ? ` (${err.filePath})` : ''}`);
                }
                if (result.errors.length > 5) {
                  console.log(`  ... and ${result.errors.length - 5} more`);
                }
              }
              return;
            } finally {
              adapter.close();
            }
          }
        } catch (cgErr) {
          // CodeGraph not loadable — fall through to legacy paths
          if (process.env.DEBUG) {
            console.error('CodeGraph error:', cgErr instanceof Error ? cgErr.message : cgErr);
          }
        }
      }

      // SQLite mode — use IncrementalSync for full index
      if (opts.sqlite) {
        if (opts.codegraph === false) {
          console.log('CodeGraph disabled, using regex analyzer...');
        } else {
          console.log('CodeGraph not available, using regex analyzer...');
        }

        const dbPath = getDatabasePath();
        const outDir = resolve('.workflow', 'codebase');
        mkdirSync(outDir, { recursive: true });

        const conn = new DatabaseConnection();
        const isNew = !existsSync(dbPath);
        if (isNew) conn.initialize(dbPath);
        else conn.open(dbPath);

        const queries = new QueryBuilder(conn);
        if (!isNew) queries.clear();

        console.log(`Indexing ${srcPath} to SQLite ...`);
        const sync = new IncrementalSync(srcPath, conn);
        const result = sync.sync();

        queries.setMetadata('projectRoot', srcPath);

        const stats = queries.getStats(conn.getSize());
        conn.close();

        if (opts.json) {
          console.log(JSON.stringify({ ...stats, ...result, output: dbPath }, null, 2));
          return;
        }

        console.log('');
        console.log(`Nodes: ${stats.nodeCount}`);
        for (const [kind, count] of Object.entries(stats.nodesByKind)) {
          console.log(`  ${kind}: ${count}`);
        }
        console.log('');
        console.log(`Edges: ${stats.edgeCount}`);
        for (const [kind, count] of Object.entries(stats.edgesByKind)) {
          console.log(`  ${kind}: ${count}`);
        }
        console.log('');
        console.log(`Files: ${stats.fileCount}`);
        console.log(`DB size: ${(stats.dbSizeBytes / 1024).toFixed(1)} KB`);
        console.log(`Duration: ${result.durationMs}ms`);
        console.log(`Written to: ${dbPath}`);
        return;
      }

      // JSON mode (legacy)
      const analyzer = new FsAnalyzer();
      console.log(`Scanning ${srcPath} ...`);

      const graph = await analyzer.analyze(srcPath);

      // If scanning a subdirectory, try to pick up project name from CWD
      const cwdPkg = resolve('package.json');
      if (existsSync(cwdPkg) && srcPath !== resolve('.')) {
        try {
          const pkg = JSON.parse(readFileSync(cwdPkg, 'utf-8'));
          if (pkg.name) graph.project.name = pkg.name;
          // Also pick up frameworks from root package.json
          const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
          const fwChecks: [string, string][] = [
            ['react', 'React'], ['vue', 'Vue'], ['angular', 'Angular'],
            ['express', 'Express'], ['fastify', 'Fastify'], ['next', 'Next.js'],
            ['nuxt', 'Nuxt'], ['commander', 'Commander'], ['ink', 'Ink'],
          ];
          const frameworks: string[] = [];
          for (const [dep, name] of fwChecks) {
            if (allDeps?.[dep]) frameworks.push(name);
          }
          if (frameworks.length > 0) graph.project.frameworks = frameworks;
        } catch { /* ignore */ }
      }

      // Ensure output directory exists
      const outDir = resolve('.workflow', 'codebase');
      mkdirSync(outDir, { recursive: true });

      const outPath = resolve(outDir, 'knowledge-graph.json');
      writeFileSync(outPath, JSON.stringify(graph, null, 2), 'utf-8');

      // Collect stats
      const nodesByType: Record<string, number> = {};
      for (const n of graph.nodes) {
        nodesByType[n.type] = (nodesByType[n.type] ?? 0) + 1;
      }
      const edgesByType: Record<string, number> = {};
      for (const e of graph.edges) {
        edgesByType[e.type] = (edgesByType[e.type] ?? 0) + 1;
      }

      const stats = {
        project: graph.project.name,
        languages: graph.project.languages,
        frameworks: graph.project.frameworks,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
        output: outPath,
      };

      if (opts.json) {
        console.log(JSON.stringify(stats, null, 2));
        return;
      }

      console.log('');
      console.log(`Project: ${stats.project}`);
      console.log(`Languages: ${stats.languages.join(', ') || 'none detected'}`);
      if (stats.frameworks.length > 0) {
        console.log(`Frameworks: ${stats.frameworks.join(', ')}`);
      }
      console.log('');
      console.log(`Nodes: ${stats.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${stats.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${stats.layers}`);
      console.log(`Tour steps: ${stats.tourSteps}`);
      console.log('');
      console.log(`Written to: ${outPath}`);
    });

  // ── sync (incremental) ────────────────────────────────────────────
  kg
    .command('sync')
    .description('Incremental sync — only re-index changed files (SQLite)')
    .option('--no-codegraph', 'Force regex-only extraction (skip tree-sitter)')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      // CodeGraph tree-sitter sync (preferred when available)
      if (opts.codegraph !== false) {
        try {
          const { isCodeGraphAvailable, CodeGraphAdapter } = await import('../graph/codegraph-adapter.js');
          if (isCodeGraphAvailable()) {
            console.log('Using CodeGraph tree-sitter engine...');
            const projectRoot = resolve('.');
            const adapter = new CodeGraphAdapter(projectRoot);
            try {
              const result = await adapter.sync();
              if (opts.json) {
                console.log(JSON.stringify({ ...result, engine: 'codegraph' }, null, 2));
              } else {
                const changed = result.filesAdded + result.filesModified + result.filesRemoved;
                console.log(`Sync complete: ${changed} files changed (${result.filesAdded} added, ${result.filesModified} modified, ${result.filesRemoved} removed), ${result.nodesUpdated} nodes updated (${result.durationMs}ms)`);
              }
              return;
            } finally {
              adapter.close();
            }
          }
        } catch {
          // CodeGraph not loadable — fall through to IncrementalSync
        }
      }

      // Fallback: IncrementalSync (regex-based)
      if (opts.codegraph === false) {
        console.log('CodeGraph disabled, using regex analyzer...');
      } else {
        console.log('CodeGraph not available, using regex analyzer...');
      }
      const { conn, queries } = openSqliteOrExit();
      try {
        const projectRoot = queries.getMetadata('projectRoot') ?? process.cwd();
        const sync = new IncrementalSync(projectRoot, conn);
        const result = sync.sync();
        if (opts.json) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          console.log(`Sync complete: ${result.filesChanged} files changed, ${result.nodesAdded} nodes, ${result.edgesAdded} edges (${result.durationMs}ms)`);
        }
      } finally {
        conn.close();
      }
    });

  // ── watch ──────────────────────────────────────────────────────────
  kg
    .command('watch')
    .description('Watch for file changes and auto-sync (SQLite)')
    .option('--debounce <ms>', 'Debounce delay in milliseconds', '2000')
    .action((opts) => {
      const dbPath = getDatabasePath();
      if (!existsSync(dbPath)) {
        console.error(`SQLite graph not found. Run "maestro kg index --sqlite" first.`);
        process.exit(1);
      }

      const conn = new DatabaseConnection();
      conn.open(dbPath);
      const queries = new QueryBuilder(conn);
      const projectRoot = queries.getMetadata('projectRoot') ?? process.cwd();
      const debounceMs = Number(opts.debounce) || 2000;

      const watcher = new FileWatcher(
        projectRoot,
        async () => {
          const sync = new IncrementalSync(projectRoot, conn);
          const result = sync.sync();
          return { filesChanged: result.filesChanged, durationMs: result.durationMs };
        },
        {
          debounceMs,
          onSyncComplete: (result) => {
            if (result.filesChanged > 0) {
              console.log(`[sync] ${result.filesChanged} files updated (${result.durationMs}ms)`);
            }
          },
          onSyncError: (err) => {
            console.error(`[sync error] ${err.message}`);
          },
        },
      );

      const started = watcher.start();
      if (!started) {
        console.error('Could not start file watcher (unsupported filesystem?)');
        conn.close();
        process.exit(1);
      }

      console.log(`Watching for changes (debounce: ${debounceMs}ms) — press Ctrl+C to stop`);

      process.on('SIGINT', () => {
        watcher.stop();
        conn.close();
        console.log('\nWatcher stopped.');
        process.exit(0);
      });
    });

  // ── callers ────────────────────────────────────────────────────────
  kg
    .command('callers <node-id>')
    .description('Show callers of a function/method')
    .option('--depth <n>', 'Max traversal depth', '2')
    .option('--json', 'Output as JSON')
    .option('--no-codegraph', 'Force regex-only (skip tree-sitter)')
    .action(async (nodeId: string, opts) => {
      const depth = Number(opts.depth) || 2;

      // Prefer CodeGraph when available
      if (opts.codegraph !== false) {
        try {
          const { isCodeGraphAvailable, CodeGraphAdapter } = await import('../graph/codegraph-adapter.js');
          if (isCodeGraphAvailable()) {
            const adapter = new CodeGraphAdapter(resolve('.'));
            try {
              if (adapter.isInitialized()) {
                const callers = await adapter.getCallers(nodeId, depth);
                if (opts.json) {
                  console.log(JSON.stringify(callers.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
                    id: c.node.id, kind: c.node.kind, name: c.node.name,
                    filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
                  })), null, 2));
                  return;
                }
                console.log(`Callers of ${nodeId} (${callers.length}):`);
                for (const { node, edge } of callers) {
                  console.log(`  [${node.kind}] ${node.id} --${edge?.kind ?? 'calls'}-->`);
                  if (node.signature) console.log(`    ${node.signature}`);
                }
                return;
              }
            } finally {
              adapter.close();
            }
          }
        } catch { /* fall through to legacy */ }
      }

      // Fallback: Maestro SQLite
      const { conn, queries } = openSqliteOrExit();
      try {
        const traverser = new GraphTraverser(queries);
        const callers = traverser.getCallers(nodeId, depth);

        if (opts.json) {
          console.log(JSON.stringify(callers.map(c => ({
            id: c.node.id, kind: c.node.kind, name: c.node.name,
            filePath: c.node.filePath, edgeKind: c.edge.kind,
          })), null, 2));
          return;
        }

        console.log(`Callers of ${nodeId} (${callers.length}):`);
        for (const { node, edge } of callers) {
          console.log(`  [${node.kind}] ${node.id} --${edge.kind}-->`);
          if (node.signature) console.log(`    ${node.signature}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── callees ────────────────────────────────────────────────────────
  kg
    .command('callees <node-id>')
    .description('Show callees of a function/method')
    .option('--depth <n>', 'Max traversal depth', '2')
    .option('--json', 'Output as JSON')
    .option('--no-codegraph', 'Force regex-only (skip tree-sitter)')
    .action(async (nodeId: string, opts) => {
      const depth = Number(opts.depth) || 2;

      // Prefer CodeGraph when available
      if (opts.codegraph !== false) {
        try {
          const { isCodeGraphAvailable, CodeGraphAdapter } = await import('../graph/codegraph-adapter.js');
          if (isCodeGraphAvailable()) {
            const adapter = new CodeGraphAdapter(resolve('.'));
            try {
              if (adapter.isInitialized()) {
                const callees = await adapter.getCallees(nodeId, depth);
                if (opts.json) {
                  console.log(JSON.stringify(callees.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
                    id: c.node.id, kind: c.node.kind, name: c.node.name,
                    filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
                  })), null, 2));
                  return;
                }
                console.log(`Callees of ${nodeId} (${callees.length}):`);
                for (const { node, edge } of callees) {
                  console.log(`  --${edge?.kind ?? 'calls'}--> [${node.kind}] ${node.id}`);
                  if (node.signature) console.log(`    ${node.signature}`);
                }
                return;
              }
            } finally {
              adapter.close();
            }
          }
        } catch { /* fall through to legacy */ }
      }

      // Fallback: Maestro SQLite
      const { conn, queries } = openSqliteOrExit();
      try {
        const traverser = new GraphTraverser(queries);
        const callees = traverser.getCallees(nodeId, depth);

        if (opts.json) {
          console.log(JSON.stringify(callees.map(c => ({
            id: c.node.id, kind: c.node.kind, name: c.node.name,
            filePath: c.node.filePath, edgeKind: c.edge.kind,
          })), null, 2));
          return;
        }

        console.log(`Callees of ${nodeId} (${callees.length}):`);
        for (const { node, edge } of callees) {
          console.log(`  --${edge.kind}--> [${node.kind}] ${node.id}`);
          if (node.signature) console.log(`    ${node.signature}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── search ─────────────────────────────────────────────────────────
  kg
    .command('search <text>')
    .description('Search nodes with optional context and wiki cross-references')
    .option('--context', 'Include caller/callee counts for each result')
    .option('--wiki', 'Include related wiki entries for each result')
    .option('--limit <n>', 'Max results', '10')
    .option('--json', 'Output as JSON')
    .option('--no-codegraph', 'Force regex-only (skip tree-sitter)')
    .action(async (text: string, opts) => {
      const limit = Number(opts.limit) || 10;

      // Prefer CodeGraph when available
      if (opts.codegraph !== false) {
        try {
          const { isCodeGraphAvailable, CodeGraphAdapter } = await import('../graph/codegraph-adapter.js');
          if (isCodeGraphAvailable()) {
            const adapter = new CodeGraphAdapter(resolve('.'));
            try {
              if (adapter.isInitialized()) {
                const cgResults = await adapter.searchNodes(text, { limit });

                const enriched: Array<{
                  id: string; kind: string; name: string; filePath: string;
                  signature?: string; isExported?: boolean;
                  callerCount?: number; calleeCount?: number;
                  wiki?: WikiMatch[];
                }> = [];

                for (const r of cgResults) {
                  const n = r.node ?? r;
                  const entry: typeof enriched[number] = {
                    id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
                    signature: n.signature || undefined,
                    isExported: n.isExported || undefined,
                  };

                  if (opts.context) {
                    const callers = await adapter.getCallers(n.id, 1);
                    const callees = await adapter.getCallees(n.id, 1);
                    entry.callerCount = callers.length;
                    entry.calleeCount = callees.length;
                  }

                  if (opts.wiki) {
                    entry.wiki = await findRelatedWikiEntries(n.id, n.filePath);
                  }

                  enriched.push(entry);
                }

                if (opts.json) {
                  console.log(JSON.stringify({ query: text, total: enriched.length, nodes: enriched, engine: 'codegraph' }, null, 2));
                  return;
                }

                console.log(`Search: "${text}"  (${enriched.length} results, CodeGraph)`);
                for (const n of enriched) {
                  const exported = n.isExported ? 'Exported ' : '';
                  const desc = n.signature ? truncate(n.signature, 60) : `${exported}${n.kind} "${n.name}" in ${n.filePath}`;
                  let line = `  [${n.kind}] ${n.id} -- ${desc}`;
                  if (n.callerCount !== undefined) {
                    line += `  (callers: ${n.callerCount}, callees: ${n.calleeCount})`;
                  }
                  console.log(line);
                  if (n.wiki && n.wiki.length > 0) {
                    for (const w of n.wiki) {
                      console.log(`    wiki: [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
                    }
                  }
                }
                return;
              }
            } finally {
              adapter.close();
            }
          }
        } catch { /* fall through to legacy */ }
      }

      // Fallback: Maestro SQLite
      const { conn, queries } = openSqliteOrExit();
      try {
        const parsed = parseQuery(text);
        const kinds = parsed.kinds.length > 0 ? parsed.kinds : undefined;
        const results = queries.searchNodes(parsed.text || text, {
          kinds,
          languages: parsed.languages.length > 0 ? parsed.languages : undefined,
          pathFilters: parsed.pathFilters.length > 0 ? parsed.pathFilters : undefined,
          nameFilters: parsed.nameFilters.length > 0 ? parsed.nameFilters : undefined,
          limit,
        });

        const traverser = opts.context ? new GraphTraverser(queries) : null;

        const enriched: Array<{
          id: string; kind: string; name: string; filePath: string;
          signature?: string; isExported?: boolean;
          callerCount?: number; calleeCount?: number;
          wiki?: WikiMatch[];
        }> = [];

        for (const n of results) {
          const entry: typeof enriched[number] = {
            id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
            signature: n.signature || undefined,
            isExported: n.isExported || undefined,
          };

          if (traverser) {
            entry.callerCount = traverser.getCallers(n.id, 1).length;
            entry.calleeCount = traverser.getCallees(n.id, 1).length;
          }

          if (opts.wiki) {
            entry.wiki = await findRelatedWikiEntries(n.id, n.filePath);
          }

          enriched.push(entry);
        }

        if (opts.json) {
          console.log(JSON.stringify({ query: text, total: enriched.length, nodes: enriched }, null, 2));
          return;
        }

        console.log(`Search: "${text}"  (${enriched.length} results, SQLite)`);
        for (const n of enriched) {
          const exported = n.isExported ? 'Exported ' : '';
          const desc = n.signature ? truncate(n.signature, 60) : `${exported}${n.kind} "${n.name}" in ${n.filePath}`;
          let line = `  [${n.kind}] ${n.id} -- ${desc}`;
          if (n.callerCount !== undefined) {
            line += `  (callers: ${n.callerCount}, callees: ${n.calleeCount})`;
          }
          console.log(line);
          if (n.wiki && n.wiki.length > 0) {
            for (const w of n.wiki) {
              console.log(`    wiki: [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
            }
          }
        }
      } finally {
        conn.close();
      }
    });

  // ── context ──────────────────────────────────────────────────────
  kg
    .command('context <node-id>')
    .description('Show full context: callers, callees, file siblings, and wiki')
    .option('--depth <n>', 'Max traversal depth', '2')
    .option('--wiki', 'Include related wiki entries')
    .option('--json', 'Output as JSON')
    .option('--no-codegraph', 'Force regex-only (skip tree-sitter)')
    .action(async (nodeId: string, opts) => {
      const depth = Number(opts.depth) || 2;

      // Prefer CodeGraph when available
      if (opts.codegraph !== false) {
        try {
          const { isCodeGraphAvailable, CodeGraphAdapter } = await import('../graph/codegraph-adapter.js');
          if (isCodeGraphAvailable()) {
            const adapter = new CodeGraphAdapter(resolve('.'));
            try {
              if (adapter.isInitialized()) {
                const resolved = await adapter.resolveNode(nodeId);
                if (resolved) {
                  const callers = await adapter.getCallers(nodeId, depth);
                  const callees = await adapter.getCallees(nodeId, depth);
                  const fileSiblings = resolved.filePath
                    ? (await adapter.getNodesInFile(resolved.filePath)).filter((n: any) => n.id !== resolved.id) // eslint-disable-line @typescript-eslint/no-explicit-any
                    : [];
                  const wikiMatches = opts.wiki
                    ? await findRelatedWikiEntries(nodeId, resolved.filePath)
                    : [];

                  if (opts.json) {
                    console.log(JSON.stringify({
                      node: {
                        id: resolved.id, kind: resolved.kind, name: resolved.name,
                        filePath: resolved.filePath, signature: resolved.signature,
                        startLine: resolved.startLine, endLine: resolved.endLine,
                        isExported: resolved.isExported,
                      },
                      callers: callers.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
                        id: c.node.id, kind: c.node.kind, name: c.node.name,
                        filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
                      })),
                      callees: callees.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
                        id: c.node.id, kind: c.node.kind, name: c.node.name,
                        filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
                      })),
                      fileSiblings: fileSiblings.map((n: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
                        id: n.id, kind: n.kind, name: n.name,
                      })),
                      wiki: wikiMatches,
                      engine: 'codegraph',
                    }, null, 2));
                    return;
                  }

                  // Text output
                  console.log(`Node: ${resolved.id}`);
                  console.log(`  Kind:       ${resolved.kind}`);
                  console.log(`  Name:       ${resolved.name}`);
                  if (resolved.filePath) console.log(`  File:       ${resolved.filePath}:${resolved.startLine}-${resolved.endLine}`);
                  if (resolved.signature) console.log(`  Signature:  ${truncate(resolved.signature, 80)}`);
                  if (resolved.isExported) console.log(`  Exported:   yes`);

                  if (callers.length > 0) {
                    console.log('');
                    console.log(`Callers (${callers.length}, depth ${depth}):`);
                    for (const { node: c, edge } of callers) {
                      console.log(`  [${c.kind}] ${c.id} --${edge?.kind ?? 'calls'}-->`);
                      if (c.signature) console.log(`    ${truncate(c.signature, 70)}`);
                    }
                  }

                  if (callees.length > 0) {
                    console.log('');
                    console.log(`Callees (${callees.length}, depth ${depth}):`);
                    for (const { node: c, edge } of callees) {
                      console.log(`  --${edge?.kind ?? 'calls'}--> [${c.kind}] ${c.id}`);
                      if (c.signature) console.log(`    ${truncate(c.signature, 70)}`);
                    }
                  }

                  if (fileSiblings.length > 0) {
                    console.log('');
                    console.log(`File siblings in ${resolved.filePath} (${fileSiblings.length}):`);
                    for (const s of fileSiblings) {
                      console.log(`  [${s.kind}] ${s.id} -- ${s.name}`);
                    }
                  }

                  if (wikiMatches.length > 0) {
                    console.log('');
                    console.log(`Related wiki entries (${wikiMatches.length}):`);
                    for (const w of wikiMatches) {
                      console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
                    }
                  }
                  return;
                }
              }
            } finally {
              adapter.close();
            }
          }
        } catch { /* fall through to legacy */ }
      }

      // Fallback: Maestro SQLite
      const { conn, queries } = openSqliteOrExit();
      try {
        const node = queries.getNodeById(nodeId);
        if (!node) {
          console.error(`Node not found: ${nodeId}`);
          process.exit(1);
        }

        const traverser = new GraphTraverser(queries);
        const callers = traverser.getCallers(nodeId, depth);
        const callees = traverser.getCallees(nodeId, depth);

        const fileSiblings = node.filePath
          ? queries.getNodesByFile(node.filePath).filter(n => n.id !== nodeId)
          : [];

        const wikiMatches = opts.wiki
          ? await findRelatedWikiEntries(nodeId, node.filePath)
          : [];

        if (opts.json) {
          console.log(JSON.stringify({
            node: {
              id: node.id, kind: node.kind, name: node.name,
              filePath: node.filePath, signature: node.signature,
              startLine: node.startLine, endLine: node.endLine,
              isExported: node.isExported,
            },
            callers: callers.map(c => ({
              id: c.node.id, kind: c.node.kind, name: c.node.name,
              filePath: c.node.filePath, edgeKind: c.edge.kind,
            })),
            callees: callees.map(c => ({
              id: c.node.id, kind: c.node.kind, name: c.node.name,
              filePath: c.node.filePath, edgeKind: c.edge.kind,
            })),
            fileSiblings: fileSiblings.map(n => ({
              id: n.id, kind: n.kind, name: n.name,
            })),
            wiki: wikiMatches,
          }, null, 2));
          return;
        }

        // Focal node
        console.log(`Node: ${node.id}`);
        console.log(`  Kind:       ${node.kind}`);
        console.log(`  Name:       ${node.name}`);
        if (node.filePath) console.log(`  File:       ${node.filePath}:${node.startLine}-${node.endLine}`);
        if (node.signature) console.log(`  Signature:  ${truncate(node.signature, 80)}`);
        if (node.isExported) console.log(`  Exported:   yes`);

        // Callers
        if (callers.length > 0) {
          console.log('');
          console.log(`Callers (${callers.length}, depth ${depth}):`);
          for (const { node: c, edge } of callers) {
            console.log(`  [${c.kind}] ${c.id} --${edge.kind}-->`);
            if (c.signature) console.log(`    ${truncate(c.signature, 70)}`);
          }
        }

        // Callees
        if (callees.length > 0) {
          console.log('');
          console.log(`Callees (${callees.length}, depth ${depth}):`);
          for (const { node: c, edge } of callees) {
            console.log(`  --${edge.kind}--> [${c.kind}] ${c.id}`);
            if (c.signature) console.log(`    ${truncate(c.signature, 70)}`);
          }
        }

        // File siblings
        if (fileSiblings.length > 0) {
          console.log('');
          console.log(`File siblings in ${node.filePath} (${fileSiblings.length}):`);
          for (const s of fileSiblings) {
            console.log(`  [${s.kind}] ${s.id} -- ${s.name}`);
          }
        }

        // Wiki
        if (wikiMatches.length > 0) {
          console.log('');
          console.log(`Related wiki entries (${wikiMatches.length}):`);
          for (const w of wikiMatches) {
            console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
          }
        }
      } finally {
        conn.close();
      }
    });

  // ── impact ─────────────────────────────────────────────────────────
  kg
    .command('impact <node-id>')
    .description('Show transitive impact radius (SQLite)')
    .option('--depth <n>', 'Max depth', '3')
    .option('--json', 'Output as JSON')
    .action((nodeId: string, opts) => {
      const { conn, queries } = openSqliteOrExit();
      try {
        const traverser = new GraphTraverser(queries);
        const subgraph = traverser.getImpactRadius(nodeId, Number(opts.depth) || 3);

        if (opts.json) {
          const nodes = [...subgraph.nodes.values()].map(n => ({
            id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
          }));
          console.log(JSON.stringify({ nodeCount: nodes.length, edgeCount: subgraph.edges.length, nodes }, null, 2));
          return;
        }

        console.log(`Impact radius for ${nodeId}: ${subgraph.nodes.size} nodes, ${subgraph.edges.length} edges`);
        for (const node of subgraph.nodes.values()) {
          if (node.id === nodeId) continue;
          console.log(`  [${node.kind}] ${node.id}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── dead-code ──────────────────────────────────────────────────────
  kg
    .command('dead-code')
    .description('Find unreferenced symbols (SQLite)')
    .option('--kinds <kinds>', 'Comma-separated node kinds to check', 'function,method,class')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const { conn, queries } = openSqliteOrExit();
      try {
        const kinds = opts.kinds.split(',').map((k: string) => k.trim());
        const manager = new GraphQueryManager(queries);
        const deadCode = manager.findDeadCode(kinds);

        if (opts.json) {
          console.log(JSON.stringify(deadCode.map(n => ({
            id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
            startLine: n.startLine, signature: n.signature,
          })), null, 2));
          return;
        }

        console.log(`Dead code (${deadCode.length} unreferenced symbols):`);
        for (const node of deadCode) {
          console.log(`  [${node.kind}] ${node.name} — ${node.filePath}:${node.startLine}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── cycles ─────────────────────────────────────────────────────────
  kg
    .command('cycles')
    .description('Find circular import dependencies (SQLite)')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const { conn, queries } = openSqliteOrExit();
      try {
        const manager = new GraphQueryManager(queries);
        const cycles = manager.findCircularDependencies();

        if (opts.json) {
          console.log(JSON.stringify(cycles, null, 2));
          return;
        }

        if (cycles.length === 0) {
          console.log('No circular dependencies detected.');
          return;
        }

        console.log(`Circular dependencies (${cycles.length}):`);
        for (let i = 0; i < cycles.length; i++) {
          console.log(`  Cycle ${i + 1}: ${cycles[i].join(' → ')} → ${cycles[i][0]}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── migrate ────────────────────────────────────────────────────────
  kg
    .command('migrate')
    .description('Convert JSON knowledge graph to SQLite')
    .option('--json', 'Output result as JSON')
    .action((opts) => {
      const jsonPath = resolve('.workflow', 'codebase', 'knowledge-graph.json');
      if (!existsSync(jsonPath)) {
        console.error(`JSON graph not found: ${jsonPath}`);
        console.error('  Hint: run "maestro kg index" to generate a JSON graph first');
        process.exit(1);
      }

      console.log('Migrating JSON graph to SQLite ...');
      const result = migrateJsonToSqlite(jsonPath);

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log(`Migrated: ${result.nodes} nodes, ${result.edges} edges`);
      console.log(`Written to: ${result.dbPath}`);
    });

  // ── export-json ────────────────────────────────────────────────────
  kg
    .command('export-json')
    .description('Export SQLite graph as JSON')
    .option('--out <path>', 'Output path', '.workflow/codebase/knowledge-graph-export.json')
    .action((opts) => {
      const dbPath = getDatabasePath();
      if (!existsSync(dbPath)) {
        console.error(`SQLite graph not found: ${dbPath}`);
        process.exit(1);
      }

      console.log('Exporting SQLite graph to JSON ...');
      const graph = exportSqliteToJson(dbPath);
      const outPath = resolve(opts.out);
      const outDir = resolve(outPath, '..');
      mkdirSync(outDir, { recursive: true });
      writeFileSync(outPath, JSON.stringify(graph, null, 2), 'utf-8');
      console.log(`Exported: ${graph.nodes.length} nodes, ${graph.edges.length} edges`);
      console.log(`Written to: ${outPath}`);
    });
}
