// Generated by scripts/generate-built-search-adapter-contract.mjs. Do not edit.
/// <reference types="node" />

export const SCHEMA_SHA256: "725be1e03b7c895d202e03f9d3377f4c787d4f7c5b3007bf968c3b5bc85d3193";
export const SEARCH_MEASUREMENT_LANES: readonly ["daemon", "semantic", "cache-load", "single-file-update", "freshness"];
export type FixedLengthArray<T, N extends number> = T[] & { length: N };

export type Provider = "wiki" | "kg" | "code" | "mixed" | "linked";

export type ProviderFunction = "WikiIndexer.searchWithMeta" | "MaestroGraph.searchUnified" | "runCodeSearch/MaestroGraph.searchCode" | "runMixedSearch" | "runCodeSearch/MaestroGraph.openReadOnly.searchCode";

export type RunnerPlatform = NodeJS.Platform;

export type QueryExpected = { queryId: string; category: string; provider: Provider; function: ProviderFunction; expectedCount: number; };

export type DatabasePaths = { canonicalDatabase: string; linkedCanonicalDatabase: string; unauthorizedControlDatabase: string; };

export type Runner = { node: string; platform: RunnerPlatform; arch: string; cpuCount: number; };

export type ProtocolConstants = { runs: 5; topK: 20; warmups: 20; measuredSamples: 100; };

export type CorpusEvidence = { expandedDocumentCount: number; wikiIndexedEntryCount: number; expandedSha256: string; };

export type SearchMeasurementLane = "daemon" | "semantic" | "cache-load" | "single-file-update" | "freshness";

export type BuiltSearchAdapterExpected = { workspaceRoot: string; qrelsSha256: string; queries: Array<QueryExpected>; databasePaths: DatabasePaths; runner: Runner; constants: ProtocolConstants; corpus?: CorpusEvidence; };

export type Provenance = { source: string; path: string; };

export type EvidenceResult = { id: string; rank: number; score: number | null; workspace: string | null; workspaceFence: string | null; authorized: boolean; status: "active" | "deprecated"; provenance: Provenance | null; };

export type EvidenceRun = { results: Array<EvidenceResult>; };

export type QueryEvidence = { queryId: string; category: string; provider: Provider; function: ProviderFunction; expectedCount: number; runs: [EvidenceRun, EvidenceRun, EvidenceRun, EvidenceRun, EvidenceRun]; };

export type EvidenceEventName = "daemon-lookup" | "daemon-start" | "filesystem-cache-read" | "filesystem-cache-write" | "filesystem-index-write" | "embedding-build" | "embedding-save" | "credibility-hit-write" | "database-attach-or-merge";

export type EvidenceEvent = { sequence: number; event: EvidenceEventName; site: string; queryId: string | null; };

export type WikiIndexSample = { durationMs: number; cacheState: "cold-build"; };

export type RawLatencyEvidence = { kgWarmSamplesMs: FixedLengthArray<number, 100>; wikiQuerySamplesMs: FixedLengthArray<number, 100>; wikiIndexWarmupSamples: FixedLengthArray<WikiIndexSample, 20>; wikiIndexSamples: FixedLengthArray<WikiIndexSample, 100>; };

export type Evidence = { queries: Array<QueryEvidence>; events: Array<EvidenceEvent>; latency: RawLatencyEvidence; };

export type RankingMetrics = { ndcgAt10: number; mrrAt10: number; recallAt20: number; };

export type AggregatedRankingMetrics = { overall: RankingMetrics; categories: Record<string, RankingMetrics>; };

export type ReportedLatency = { kgWarmP95Ms: number; kgWarmMaxMs: number; wikiQueryP95Ms: number; wikiIndexP95Ms: number; };

export type ReportedIntegrity = { deprecatedLeakCount: number; unauthorizedWorkspaceHitCount: number; provenanceLossCount: number; attachOrMergeCalls: number; };

export type ReportedSideEffects = { daemonLookupCalls: number; daemonStartCalls: number; filesystemCacheReadCalls: number; filesystemCacheWriteCalls: number; filesystemIndexWriteCalls: number; embeddingBuildCalls: number; embeddingSaveCalls: number; credibilityHitWriteCalls: number; };

export type ReportedAggregates = { metrics: AggregatedRankingMetrics; overallNdcgGain: number; maxCategoryNdcgDrop: number; stability: { runs: 5; topK: 20; stableTop20: boolean; }; latency: ReportedLatency; integrity: ReportedIntegrity; sideEffects: ReportedSideEffects; };

export type FileIdentity = { size: number; mtimeMs: number; sha256: string; };

export type ProtectedState = { before: Record<string, FileIdentity>; after: Record<string, FileIdentity>; unchanged: true; };

export type WorkspaceEvidence = { root: string; cwd: string; maestroProjectRoot: string; canonicalDatabase: string; linkedCanonicalDatabase: string; unauthorizedControlDatabase: string; persistence: "memory-only"; executionMode: "read-only-probe"; };

export type BuiltSearchAdapterReport = { schema_version: "built-search-adapter/1.1"; ok: true; qrelsSha256: string; corpus?: CorpusEvidence; evidence: Evidence; reported: ReportedAggregates; workspace: WorkspaceEvidence; protectedState: ProtectedState; runner: Runner; };

export type BuiltSearchAdapterFixtureInput = { expected: BuiltSearchAdapterExpected; queryRuns: Record<string, [EvidenceRun, EvidenceRun, EvidenceRun, EvidenceRun, EvidenceRun]>; events: Array<EvidenceEvent>; kgWarmSamplesMs: FixedLengthArray<number, 100>; wikiQuerySamplesMs: FixedLengthArray<number, 100>; wikiIndexWarmupSamples: FixedLengthArray<WikiIndexSample, 20>; wikiIndexSamples: FixedLengthArray<WikiIndexSample, 100>; protectedState: ProtectedState; reportedOverrides: Record<string, unknown> | null; };

export function parseBuiltSearchAdapterExpected(value: unknown): BuiltSearchAdapterExpected;
export function parseBuiltSearchAdapterReport(
  value: unknown,
  expected: BuiltSearchAdapterExpected,
): BuiltSearchAdapterReport;
export function makeBuiltSearchAdapterFixture(
  input: BuiltSearchAdapterFixtureInput,
): BuiltSearchAdapterReport;
